prostage_accueil:
  path: /
  controller: App\Controller\ProStageController::index

prostage_stages_entreprise:
  path: /entreprise/{idEntreprise}
  controller: App\Controller\ProStageController::afficherStagesEntreprise

prostage_ressource:
  path: /stage/{idStage}
  controller: App\Controller\ProStageController::afficherStage
 
prostage_liste_entreprises:
  path: /entreprises/
  controller: App\Controller\ProStageController::afficherEntreprises
  
prostage_formations:
  path: /formations/
  controller: App\Controller\ProStageController::afficherFormations
